server:
  port: 8070
spring:
  application:
    name: hostel-manage
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    hostel-user: ##用户
      path: /api-user/**
      serviceId: hostel-user
