server:
  port: 8080
spring:
  application:
    name: hostel-web
eureka:
  client:
    service-url: ##配置中心地址
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes: #配置网关路由
    hostel-user: ##用户
      path: /api-user/**
      serviceId: hostel-user
